---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: directory
  path: src/shop/categories
  label: Shop Categories
  create: documents
  match: "*.md"
  templates:
  - shop-category
- type: directory
  path: src/shop/products
  label: Shop Products
  create: documents
  match: "*.md"
  templates:
  - shop-product
- type: document
  path: src/_data/banner_message.json
  label: Banner Message
- type: document
  path: src/_data/site_data.json
  label: Site Data
upload_dir: ''
public_path: https://res.cloudinary.com/floriade/image/upload
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:16
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run serve
