module.exports = {
  INSTAGRAM_TOKEN: process.env.INSTAGRAM_TOKEN,
  STRIPE_TEST_PUBLIC_KEY: process.env.STRIPE_TEST_PUBLIC_KEY,
  STRIPE_LIVE_PUBLIC_KEY: process.env.STRIPE_LIVE_PUBLIC_KEY,
  RECAPTCHA_SITE_KEY: process.env.RECAPTCHA_SITE_KEY,
  RECAPTCHA_SECRET_KEY: process.env.RECAPTCHA_SECRET_KEY,
  GOOGLE_PLACE_ID: process.env.GOOGLE_PLACE_ID,
  GOOGLE_MAPS_KEY: process.env.GOOGLE_MAPS_KEY
};
